### ISSUE TITLE
Missed some lines

### ISSUE THREAD

**Issue by gregor160300** [SlimLP-Y300/android_device_huawei_u8833#2]
device/huawei/u8833/audio/AudioHardware_cad.cpp:2553:23: error: 'EVRC' is not a member of 'android_audio_legacy::AudioSystem'
          (_pFormat != AudioSystem::EVRC) &&
                       ^
device/huawei/u8833/audio/AudioHardware_cad.cpp:2554:23: error: 'QCELP' is not a member of 'android_audio_legacy::AudioSystem'
          (_pFormat != AudioSystem::QCELP) &&
                       ^
device/huawei/u8833/audio/AudioHardware_cad.cpp:2646:27: error: 'EVRC' is not a member of 'android_audio_legacy::AudioSystem'
              (_pFormat == AudioSystem::EVRC) ||
                           ^
device/huawei/u8833/audio/AudioHardware_cad.cpp:2647:27: error: 'QCELP' is not a member of 'android_audio_legacy::AudioSystem'
              (_pFormat == AudioSystem::QCELP))
                           ^

**Comment by sunnyden** [comment]
apply this patch:https://github.com/SlimLP-Y300/android_device_huawei_msm7x27a-common/blob/lp5.0/patches/hardware_libhardware_legacy/0002-audio-formats.patch
