### ISSUE TITLE
Does this ROM come with CDMA phone call support?

### ISSUE THREAD

**Issue by yangxuan8282** [SlimLP-Y300/android_device_huawei_u8833#4]
I have a Huawei C8813D, pretty same with G510,which is Snapdragon MSM8625, 512M RAM, but come with CDMA dual SIM card instead of GSM.
I flash Slim-u8833-5.1.1.beta.0.14-UNOFFICIAL-20160107-2248 on my phone, everythiny works great.It runs so smooth. Everything works except phone function, no signal.
Can you help me with this issues? Thanks.
I know maybe it's not proper post issues here, since they are different model.But I really hope this ROM run full function on my old phone.

**Comment by Meliodas377** [comment]
Well, that's a problem because all ROM's of that model is based on RIL for
GSM, not for CDMA phones, I really want help you with that problem but it's
not possible without the necessary files.

2016-02-05 6:48 GMT-04:30 yangxuan8282 notifications@github.com:

**Comment by yangxuan8282** [comment]
@Meliodas377 What a pity, since it's a so nice ROM
